# Developed by Eng Mouaz M AlShahmeh
name: doodle_dash_flutter_flame_game
description: Developed by Eng Mouaz M AlShahmeh
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flame: ^1.6.0
  google_fonts: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/game/
    - assets/images/game/background/